name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      project:
        type: string
        required: true

      environment:
        type: string
        required: true

jobs:
  validate:
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      project: ${{ inputs.project }}
      environment: ${{ inputs.environment }}
      terraform_command: validate

  plan:
    needs: validate

    uses: ./.github/workflows/reusable-terraform.yml
    with:
      project: ${{ inputs.project }}
      environment: ${{ inputs.environment }}
      terraform_command: plan