name: Reusable Terraform

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

      environment:
        required: true
        type: string

      aws_region:
        required: true
        type: string

      role_arn:
        required: true
        type: string

      tf_version:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: stacks/${{ inputs.project }}/${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - uses: terraform-linters/setup-tflint@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.role_arn }}

      - name: Terraform Init
        run: terraform init

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Validate
        run: terraform validate

      - name: TFLint Init
        run: tflint --init

      - name: TFLint
        run: tflint --recursive

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          severity: HIGH,CRITICAL
          exit-code: "1"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ inputs.project }}-${{ inputs.environment }}
          path: stacks/${{ inputs.project }}/${{ inputs.environment }}/tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest

    environment: ${{ format('{0}-{1}', inputs.project, inputs.environment) }}

    defaults:
      run:
        shell: bash
        working-directory: stacks/${{ inputs.project }}/${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.role_arn }}

      - name: Terraform Init
        run: terraform init

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ inputs.project }}-${{ inputs.environment }}
          path: stacks/${{ inputs.project }}/${{ inputs.environment }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan