name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        options: [tms, api]

      environment:
        type: choice
        options: [dev, stage, prod]

      aws_region:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      aws_region: ${{ steps.config.outputs.aws_region }}
      role_arn: ${{ steps.config.outputs.role_arn }}
      tf_version: ${{ steps.config.outputs.tf_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read accounts.json
        id: config
        shell: bash
        run: |
          ROLE_ARN=$(jq -r \
            --arg project "${{ inputs.project }}" \
            --arg env "${{ inputs.environment }}" \
            '.projects[$project][$env].role_arn' \
            accounts.json)

          echo "role_arn=$ROLE_ARN" >> "$GITHUB_OUTPUT"

  terraform:
    needs: setup

    uses: ./.github/workflows/reusable-terraform.yml

    with:
      project: ${{ inputs.project }}
      environment: ${{ inputs.environment }}
      aws_region: ${{ inputs.aws_region }}
      role_arn: ${{ needs.setup.outputs.role_arn }}
      tf_version: "1.15.7"